### ISSUE TITLE
Why is get() used when processing effects

### ISSUE THREAD

**Issue by zupat** [modderme123/reactively#21]
https://github.com/modderme123/reactively/blob/9081fa4bf302a5f768962e0a4421a28d705439ff/packages/core/src/core.ts#L318

Wouldn't ` EffectQueue[i].updateIfNecessary() ` achieve the same behavior while doing a bit less work?

**Comment by milomg** [comment]
Yes. However, `updateIfNecessary` is currently internal (private), and the scheduler is a bit more external and (somewhat intentionally) cannot access all of the internals.
