### ISSUE TITLE
untrack

### ISSUE THREAD

**Issue by xdadda** [modderme123/reactively#23]
Hi, nice library.
I'm currently experimenting with it.
Assuming I have autostabilze() run at the beginning of my code... how would you implement an "untrack" function similar to Signal's to use inside react(()=>{ ..... code here ..... },{effect:true}) ??

thanks

**Comment by milomg** [comment]
A simple implementation might be:

```ts
export function untrack<T>(fn: () => T): T {
  const prevReaction = CurrentReaction;
  const prevGets = CurrentGets;
  const prevIndex = CurrentGetsIndex;

  CurrentReaction = undefined;
  CurrentGets = null as any;
  CurrentGetsIndex = 0;

  const out = fn();

  CurrentGets = prevGets;
  CurrentReaction = prevReaction;
  CurrentGetsIndex = prevIndex;

  return out;
}
```

Note that this can (and most likely will) break from-scratch consistency which is why it isn't provided by default.

**Comment by xdadda** [comment]
thanks. I will give it a try! excellent work with this library btw
